### ISSUE TITLE
[ZMQ] compilation error

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle-plugin-cluster#52]
while installing npm dependencies without zeromq library, the process fails with following error:
`../binding.cc:28:17: fatal error: zmq.h: No such file or directory`
and we cannot use the plugin.

The readme need to explain this requirements and how to install the needed library (see https://www.npmjs.com/package/zmq#installation )

**Comment by scottinet** [comment]
The REA

**Comment by Aschen** [comment]
@scottinet Documented where? I didn't find it in the README

**Comment by scottinet** [comment]
... I might have mistaken this issue with a MQTT one :expressionless:
